#!/usr/bin/env python3
"""Données UNIQUES par secteur (pages mères / pôles) pour le déploiement du modèle.
Maillage descendant : chaque secteur pointe vers son article, des secteurs liés et
des pages locales (zones). Contenu, prestations et FAQ propres à chaque secteur."""

# services : liste de (prestation, détail, fréquence)
SECTORS = {
    "ascenseurs-escalators": dict(
        name="Ascenseurs & Escalators", short="ascenseurs & escalators", zone="Paris & Île-de-France",
        title="Nettoyage d'ascenseurs & escalators à Paris & Île-de-France | SPN NET",
        desc="Nettoyage d'ascenseurs et escalators à Paris et en IDF : cabines, inox, miroirs, portes, marches. Partenaire des ascensoristes. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage ascenseurs & escalators · Paris & Île-de-France",
        h1="Nettoyage d'<em>ascenseurs & d'escalators</em>",
        lead="Cabines, portes palières, inox, miroirs, marches et peignes d'escalators : une propreté impeccable pour des équipements très sollicités et très visibles. Partenaire des ascensoristes et des gestionnaires. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Ascenseurs et escalators comptent parmi les équipements les plus visibles et les plus touchés d'un immeuble : cabines, parois inox, miroirs, portes palières, marches et peignes se salissent vite et demandent un entretien spécifique.",
        p2="Nous en avons fait une spécialité, aux côtés des grands acteurs de l'ascenseur (OTIS, KONE, Schindler…) et des gestionnaires d'immeubles. Nos agents utilisent des produits adaptés à l'inox et au vitrage, et interviennent en horaires décalés.",
        aspects=["Cabines", "Parois inox", "Miroirs & vitrage", "Portes palières", "Marches d'escalators", "Peignes & seuils"],
        services=[
            ("Cabines d'ascenseur", "Parois, sol, plafond, boutons et points de contact", "Régulier"),
            ("Inox & miroirs", "Détachage et lustrage de l'inox et des surfaces vitrées", "Régulier"),
            ("Portes palières", "Nettoyage des portes et encadrements à chaque niveau", "Régulier"),
            ("Escalators", "Marches, mains courantes, joints et peignes", "Régulier"),
            ("Vitrage & abords", "Gaines vitrées, seuils et abords immédiats", "Périodique"),
        ],
        faq=[("Travaillez-vous avec les ascensoristes ?",
              "Oui, nous intervenons en partenariat avec des sociétés d'ascenseurs et des gestionnaires d'immeubles, sur des équipements neufs comme anciens."),
             ("Utilisez-vous des produits adaptés à l'inox et au vitrage ?",
              "Oui, les cabines, l'inox et les surfaces vitrées sont traités avec des produits et méthodes adaptés, pour éviter traces et rayures.")],
        article=("ascenseurs", "Ascenseurs — en savoir plus"),
        related=[("escalators", "Escalators"), ("copropriete-et-habitat", "Copropriété & Habitat")],
        zones=[("paris-8", "Paris 8e"), ("paris-15", "Paris 15e"), ("92-hauts-de-seine", "Hauts-de-Seine (92)"), ("94-val-de-marne", "Val-de-Marne (94)")],
    ),
    "tertiaire": dict(
        name="Bureaux & Tertiaire", short="Bureaux & Tertiaire", zone="Paris & Île-de-France",
        title="Nettoyage de bureaux & tertiaire à Paris & Île-de-France | SPN NET",
        desc="Entreprise de nettoyage de bureaux et de locaux tertiaires à Paris et en Île-de-France. Interventions soir & matin, ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Nettoyage tertiaire · Paris & Île-de-France",
        h1="Nettoyage de <em>bureaux & de locaux tertiaires</em>",
        lead="Sièges, plateaux de bureaux, espaces de coworking : nous assurons l'entretien de vos locaux tertiaires à Paris et en Île-de-France. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans gêner votre activité. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le tertiaire est notre cœur de métier : bureaux, sièges sociaux, plateaux ouverts, salles de réunion et espaces de coworking. Nous intervenons pour des PME comme pour de grands comptes, sur un ou plusieurs sites.",
        p2="La propreté d'un bureau soutient le bien-être des équipes et l'image auprès des visiteurs. Nos agents interviennent en horaires décalés, avec un protocole clair et un contrôle qualité régulier.",
        aspects=["Postes de travail", "Sanitaires", "Sols & moquettes", "Vitrerie", "Salles de réunion", "Tisaneries & cuisines"],
        services=[
            ("Entretien des bureaux", "Dépoussiérage, surfaces, corbeilles, désinfection des points de contact", "Quotidien / 3× sem."),
            ("Sanitaires", "Nettoyage complet, désinfection et réassort des consommables", "Quotidien"),
            ("Sols", "Aspiration, lavage, décapage et cristallisation selon le revêtement", "Selon protocole"),
            ("Vitrerie", "Surfaces vitrées, cloisons, portes et vitrines", "Mensuel / trimestriel"),
            ("Moquettes & textiles", "Shampouinage et injection-extraction", "Ponctuel / semestriel"),
        ],
        faq=[("Intervenez-vous pour les grands plateaux et les sièges ?",
              "Oui, du petit bureau au grand siège multi-étages. Le protocole et la fréquence sont définis lors du devis selon vos surfaces et vos flux."),
             ("Travaillez-vous avec les espaces de coworking ?",
              "Oui : coworkings et espaces partagés font partie des locaux que nous entretenons, avec une organisation adaptée à ces usages.")],
        article=("meilleure-entreprise-nettoyage-tertiaire-paris", "Guide : nettoyage tertiaire à Paris"),
        related=[("commerce-et-retail", "Commerce & Retail"), ("copropriete-et-habitat", "Copropriété & Habitat")],
        zones=[("paris-2", "Paris 2e"), ("paris-8", "Paris 8e"), ("paris-15", "Paris 15e"), ("92-hauts-de-seine", "Hauts-de-Seine (92)")],
    ),
    "commerce-et-retail": dict(
        name="Commerce & Retail", short="Commerce & Retail", zone="Paris & Île-de-France",
        title="Nettoyage de commerces & retail à Paris & Île-de-France | SPN NET",
        desc="Nettoyage de commerces, boutiques et surfaces de vente à Paris et en IDF : vitrines, sols, sanitaires. ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Nettoyage commerce & retail · Paris & Île-de-France",
        h1="Nettoyage de <em>commerces & de surfaces de vente</em>",
        lead="Boutiques, enseignes, showrooms et centres commerciaux : nous garantissons des espaces de vente impeccables, accueillants pour vos clients. Interventions <span class=\"hl\">avant l'ouverture ou après la fermeture</span>. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Dans le retail, la propreté est un argument commercial direct : vitrines nettes, sols brillants, cabines et sanitaires irréprochables conditionnent l'expérience d'achat et l'image de l'enseigne.",
        p2="Nous intervenons hors des heures d'ouverture pour ne jamais gêner la vente, avec une régularité qui maintient le point de vente au meilleur niveau toute l'année.",
        aspects=["Vitrines & devantures", "Surfaces de vente", "Sols (carrelage, parquet)", "Cabines d'essayage", "Sanitaires", "Réserves"],
        services=[
            ("Surfaces de vente", "Sols, rayonnages accessibles, mobilier, points de contact", "Quotidien / avant ouverture"),
            ("Vitrines & devantures", "Vitres intérieures et extérieures, portes", "Régulier"),
            ("Sanitaires & cabines", "Nettoyage, désinfection, réassort", "Quotidien"),
            ("Sols", "Lavage mécanisé, décapage, cristallisation", "Selon revêtement"),
            ("Réserves & communs", "Entretien des zones techniques et de stockage", "Selon besoin"),
        ],
        faq=[("Intervenez-vous avant l'ouverture du magasin ?",
              "Oui, tôt le matin avant l'arrivée des clients ou le soir après la fermeture, pour ne pas perturber la vente."),
             ("Gérez-vous les vitrines et devantures ?",
              "Oui, la vitrerie (intérieure et extérieure, devantures, portes) fait partie des prestations, à la fréquence définie au devis.")],
        article=("meilleure-entreprise-nettoyage-commerce-retail-paris", "Guide : nettoyage de commerces à Paris"),
        related=[("tertiaire", "Bureaux & Tertiaire"), ("hotellerie-et-restauration", "Hôtellerie & Restauration")],
        zones=[("paris-1", "Paris 1er"), ("paris-4", "Paris 4e"), ("paris-8", "Paris 8e"), ("paris-9", "Paris 9e")],
    ),
    "sante-et-medical": dict(
        name="Santé & Médical", short="Santé & Médical", zone="Paris & Île-de-France",
        title="Nettoyage médical & bionettoyage à Paris & Île-de-France | SPN NET",
        desc="Bionettoyage de cabinets, laboratoires, cliniques et EHPAD à Paris et en IDF : protocoles d'hygiène, traçabilité. ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Bionettoyage & hygiène médicale · Paris & Île-de-France",
        h1="<em>Bionettoyage</em> médical & santé",
        lead="Cabinets, laboratoires, cliniques, maisons de santé, EHPAD : nous appliquons des protocoles d'hygiène rigoureux, adaptés aux environnements de soin. Agents formés, traçabilité et discrétion. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Les établissements de santé exigent bien plus qu'un nettoyage classique : un bionettoyage, avec code couleur, protocoles de désinfection et respect des zones à risque, pour maîtriser le risque infectieux.",
        p2="Nos agents formés interviennent selon des procédures traçables, adaptées à chaque zone (salle d'attente, cabinet, laboratoire, sanitaires). Les modalités précises sont définies lors de l'étude de votre besoin.",
        aspects=["Salles d'attente", "Cabinets de soin", "Laboratoires", "Sanitaires", "Zones à risque", "Traçabilité"],
        services=[
            ("Bionettoyage des salles", "Désinfection des surfaces et points de contact, code couleur", "Quotidien / selon zone"),
            ("Sanitaires", "Nettoyage et désinfection renforcés, réassort", "Quotidien"),
            ("Sols", "Lavage et désinfection adaptés aux environnements de soin", "Quotidien"),
            ("Salles d'attente & accueil", "Entretien fréquent des zones de passage", "Quotidien"),
            ("Vitrerie & communs", "Surfaces vitrées, parties communes", "Régulier"),
        ],
        faq=[("Vos agents sont-ils formés au bionettoyage ?",
              "Oui, nos agents sont formés aux protocoles d'hygiène et de désinfection propres aux environnements de santé (code couleur, zones à risque)."),
             ("Adaptez-vous les protocoles à chaque établissement ?",
              "Oui, cabinet, laboratoire, clinique ou EHPAD : le protocole, les produits et la fréquence sont définis lors de l'étude de votre besoin.")],
        article=("meilleure-entreprise-nettoyage-sante-medical-paris", "Guide : nettoyage médical à Paris"),
        related=[("tertiaire", "Bureaux & Tertiaire"), ("enseignement-et-petite-enfance", "Enseignement & Petite Enfance")],
        zones=[("paris-14", "Paris 14e"), ("paris-13", "Paris 13e"), ("92-hauts-de-seine", "Hauts-de-Seine (92)"), ("94-val-de-marne", "Val-de-Marne (94)")],
    ),
    "logistique-et-industrie": dict(
        name="Logistique & Industrie", short="Logistique & Industrie", zone="Paris & Île-de-France",
        title="Nettoyage industriel & logistique à Paris & Île-de-France | SPN NET",
        desc="Nettoyage d'entrepôts, plateformes logistiques et sites industriels en IDF : sols mécanisés, autolaveuse, quais. ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Nettoyage industriel & logistique · Île-de-France",
        h1="Nettoyage <em>industriel & logistique</em>",
        lead="Entrepôts, plateformes logistiques, ateliers et sites industriels : nous entretenons de grandes surfaces avec des moyens mécanisés et des équipes habituées aux contraintes de production. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Les sites logistiques et industriels imposent des enjeux spécifiques : grandes surfaces, sols techniques, quais, zones de circulation d'engins et normes de sécurité strictes.",
        p2="Nous mobilisons des moyens adaptés (autolaveuses, protocoles sols industriels) et des agents formés à la sécurité, en intervenant sur des créneaux compatibles avec votre activité.",
        aspects=["Entrepôts", "Quais de chargement", "Sols techniques", "Bureaux d'exploitation", "Sanitaires & vestiaires", "Autolaveuse"],
        services=[
            ("Sols industriels", "Lavage mécanisé (autolaveuse), décapage, traitement", "Selon protocole"),
            ("Quais & circulations", "Nettoyage des zones de flux et de chargement", "Régulier"),
            ("Bureaux d'exploitation", "Entretien des espaces administratifs du site", "Quotidien / 3× sem."),
            ("Sanitaires & vestiaires", "Nettoyage et désinfection, réassort", "Quotidien"),
            ("Vitrerie & communs", "Surfaces vitrées, réfectoires, parties communes", "Régulier"),
        ],
        faq=[("Disposez-vous de moyens mécanisés pour les grandes surfaces ?",
              "Oui, nous utilisons des autolaveuses et des protocoles adaptés aux sols techniques des entrepôts et sites industriels."),
             ("Intervenez-vous sur des créneaux compatibles avec la production ?",
              "Oui, nous nous organisons sur des horaires qui ne perturbent pas votre exploitation, y compris tôt, tard ou le week-end.")],
        article=("meilleure-entreprise-nettoyage-logistique-industrie-paris", "Guide : nettoyage logistique à Paris"),
        related=[("tertiaire", "Bureaux & Tertiaire"), ("commerce-et-retail", "Commerce & Retail")],
        zones=[("94-val-de-marne", "Val-de-Marne (94)"), ("93-seine-saint-denis", "Seine-Saint-Denis (93)"), ("95-val-doise", "Val-d'Oise (95)"), ("77-seine-et-marne", "Seine-et-Marne (77)")],
    ),
    "hotellerie-et-restauration": dict(
        name="Hôtellerie & Restauration", short="Hôtellerie & Restauration", zone="Paris & Île-de-France",
        title="Nettoyage d'hôtels & restaurants à Paris & Île-de-France | SPN NET",
        desc="Nettoyage d'hôtels, restaurants et brasseries à Paris : parties communes, chambres, dégraissage de cuisines. ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Propreté hôtelière & restauration · Paris & Île-de-France",
        h1="Nettoyage d'<em>hôtels & de restaurants</em>",
        lead="Hôtels, restaurants, brasseries : un entretien rigoureux qui protège votre réputation et le confort de vos clients. Interventions de nuit ou hors service. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Dans l'hôtellerie-restauration, la propreté est indissociable de l'expérience client : parties communes, chambres, salles, sanitaires et cuisines doivent être irréprochables en permanence.",
        p2="Nous intervenons de nuit ou hors service pour ne jamais gêner l'exploitation, avec des protocoles adaptés aux zones à forte exigence d'hygiène comme les cuisines.",
        aspects=["Parties communes", "Chambres", "Salles & réceptions", "Sanitaires", "Cuisines & plonge", "Vitrerie"],
        services=[
            ("Parties communes & réception", "Halls, couloirs, ascenseurs, mobilier, points de contact", "Quotidien"),
            ("Sanitaires", "Nettoyage et désinfection, réassort des consommables", "Quotidien / plusieurs fois"),
            ("Salles & espaces de restauration", "Sols, surfaces, remise en ordre", "Après service"),
            ("Cuisines", "Nettoyage et dégraissage des zones de production", "Selon protocole"),
            ("Vitrerie", "Surfaces vitrées, devantures, verrières", "Régulier"),
        ],
        faq=[("Intervenez-vous de nuit ou hors service ?",
              "Oui, nous nous adaptons aux contraintes de l'hôtellerie-restauration : interventions de nuit, tôt le matin ou entre les services."),
             ("Prenez-vous en charge le dégraissage des cuisines ?",
              "Oui, le nettoyage et le dégraissage des zones de cuisine font partie des prestations, selon un protocole défini avec vous.")],
        article=("meilleure-entreprise-nettoyage-hotellerie-restauration-paris", "Guide : nettoyage d'hôtels à Paris"),
        related=[("commerce-et-retail", "Commerce & Retail"), ("loisirs-culture-et-evenementiel", "Loisirs & Événementiel")],
        zones=[("paris-1", "Paris 1er"), ("paris-8", "Paris 8e"), ("paris-9", "Paris 9e"), ("paris-2", "Paris 2e")],
    ),
    "copropriete-et-habitat": dict(
        name="Copropriété & Habitat", short="Copropriété & Habitat", zone="Paris & Île-de-France",
        title="Nettoyage de copropriétés & d'immeubles à Paris & IDF | SPN NET",
        desc="Nettoyage de copropriétés et parties communes d'immeubles à Paris et en IDF : halls, escaliers, locaux poubelles, sorties de bacs. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Propreté des copropriétés · Paris & Île-de-France",
        h1="Nettoyage de <em>copropriétés & d'immeubles</em>",
        lead="Halls, escaliers, ascenseurs, locaux techniques et sorties de conteneurs : nous entretenons les parties communes de vos immeubles, pour des résidents satisfaits et un patrimoine valorisé. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="La propreté des parties communes est le premier signe de qualité d'une copropriété : halls, cages d'escalier, ascenseurs, paliers et locaux poubelles conditionnent le cadre de vie et la valeur du bien.",
        p2="Nous travaillons avec syndics et gestionnaires sur des prestations régulières et fiables, incluant la gestion des sorties et rentrées de conteneurs selon le calendrier de collecte.",
        aspects=["Halls & entrées", "Cages d'escalier", "Ascenseurs", "Paliers", "Locaux poubelles", "Sorties de bacs"],
        services=[
            ("Parties communes", "Halls, escaliers, paliers, ascenseurs, points de contact", "1 à 6× / semaine"),
            ("Sorties & rentrées de bacs", "Manipulation des conteneurs selon la collecte", "Selon calendrier"),
            ("Locaux poubelles", "Nettoyage et désinfection des locaux déchets", "Régulier"),
            ("Vitrerie des communs", "Portes, hall, fenêtres des parties communes", "Périodique"),
            ("Abords & extérieurs", "Entretien des accès et espaces extérieurs communs", "Selon besoin"),
        ],
        faq=[("Travaillez-vous avec les syndics et gestionnaires ?",
              "Oui, nous intervenons pour les syndics, gestionnaires et bailleurs, avec un interlocuteur dédié et des prestations régulières."),
             ("Gérez-vous les sorties de conteneurs ?",
              "Oui, la sortie et la rentrée des bacs peuvent être intégrées à la prestation, selon le calendrier de collecte de votre commune.")],
        article=("meilleure-entreprise-nettoyage-copropriete-habitat-paris", "Guide : nettoyage de copropriétés à Paris"),
        related=[("tertiaire", "Bureaux & Tertiaire"), ("commerce-et-retail", "Commerce & Retail")],
        zones=[("paris-15", "Paris 15e"), ("paris-16", "Paris 16e"), ("92-hauts-de-seine", "Hauts-de-Seine (92)"), ("94-val-de-marne", "Val-de-Marne (94)")],
    ),
    "loisirs-culture-et-evenementiel": dict(
        name="Loisirs, Culture & Événementiel", short="Loisirs & Événementiel", zone="Paris & Île-de-France",
        title="Nettoyage culturel, loisirs & événementiel à Paris & IDF | SPN NET",
        desc="Nettoyage de musées, théâtres, cinémas, salles de sport et de sites événementiels à Paris et en IDF. Interventions avant/après public. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Propreté culturelle & événementielle · Paris & Île-de-France",
        h1="Nettoyage <em>culturel, loisirs & événementiel</em>",
        lead="Musées, théâtres, cinémas, salles de concert et de sport, sites recevant du public : des espaces impeccables avant l'arrivée de vos visiteurs. Interventions discrètes, en horaires décalés. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Les lieux culturels, sportifs et événementiels accueillent un public nombreux : la propreté y est un enjeu d'image et de confort, dans des espaces souvent vastes et sensibles.",
        p2="Nous intervenons avant l'ouverture ou après la fermeture au public, y compris pour des remises en état après événement, avec des équipes discrètes et réactives.",
        aspects=["Halls & accueil", "Salles & gradins", "Sanitaires publics", "Sols & vitrages", "Coulisses & loges", "Après-événement"],
        services=[
            ("Espaces recevant du public", "Halls, salles, gradins, points de contact", "Avant / après public"),
            ("Sanitaires publics", "Nettoyage et désinfection à forte fréquence, réassort", "Plusieurs fois / jour"),
            ("Sols & vitrages", "Lavage mécanisé, surfaces vitrées, entrées", "Régulier"),
            ("Coulisses & espaces techniques", "Loges, réserves, zones privées", "Selon besoin"),
            ("Remise en état après événement", "Grand nettoyage post-manifestation", "Ponctuel"),
        ],
        faq=[("Intervenez-vous avant l'ouverture au public ?",
              "Oui, nos équipes interviennent avant l'accueil du public ou après la fermeture, de façon discrète, pour des espaces impeccables."),
             ("Assurez-vous la remise en état après un événement ?",
              "Oui, nous réalisons des remises en état ponctuelles après manifestation, en complément de l'entretien régulier.")],
        article=("meilleure-entreprise-nettoyage-loisirs-culture-evenementiel-paris", "Guide : nettoyage culturel à Paris"),
        related=[("hotellerie-et-restauration", "Hôtellerie & Restauration"), ("enseignement-et-petite-enfance", "Enseignement & Petite Enfance")],
        zones=[("paris-1", "Paris 1er"), ("paris-8", "Paris 8e"), ("paris-19", "Paris 19e"), ("93-seine-saint-denis", "Seine-Saint-Denis (93)")],
    ),
    "enseignement-et-petite-enfance": dict(
        name="Enseignement & Petite Enfance", short="Enseignement & Petite Enfance", zone="Paris & Île-de-France",
        title="Nettoyage d'écoles & crèches à Paris & Île-de-France | SPN NET",
        desc="Nettoyage d'écoles, universités, crèches et établissements de petite enfance à Paris et en IDF : hygiène renforcée, produits adaptés. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Propreté scolaire & petite enfance · Paris & Île-de-France",
        h1="Nettoyage d'<em>écoles & de crèches</em>",
        lead="Écoles, universités, centres de formation, crèches et haltes-garderies : une hygiène renforcée pour la santé des enfants et des équipes. Interventions hors présence. Certifiés ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Les établissements d'enseignement et de petite enfance demandent une hygiène irréprochable : salles de classe, dortoirs, réfectoires et sanitaires accueillent un public jeune et sensible.",
        p2="Nous appliquons des protocoles de désinfection adaptés, avec des produits et une organisation pensés pour intervenir hors de la présence des enfants.",
        aspects=["Salles de classe", "Dortoirs & espaces de repos", "Réfectoires", "Sanitaires", "Aires de jeux", "Désinfection"],
        services=[
            ("Salles & espaces d'accueil", "Surfaces, mobilier, sols, points de contact", "Quotidien"),
            ("Sanitaires", "Nettoyage et désinfection renforcés, réassort", "Quotidien / plusieurs fois"),
            ("Réfectoires", "Entretien et désinfection après les repas", "Quotidien"),
            ("Dortoirs & espaces de repos", "Nettoyage adapté aux espaces petite enfance", "Quotidien"),
            ("Sols & vitrerie", "Lavage des sols, surfaces vitrées", "Régulier"),
        ],
        faq=[("Intervenez-vous en dehors de la présence des enfants ?",
              "Oui, nos interventions sont organisées hors présence des élèves ou des enfants (tôt, tard ou pendant les fermetures)."),
             ("Utilisez-vous des produits adaptés à la petite enfance ?",
              "Les produits et protocoles adaptés à ces environnements sensibles sont définis lors de l'étude de votre besoin.")],
        article=("meilleure-entreprise-nettoyage-enseignement-petite-enfance-paris", "Guide : nettoyage d'écoles à Paris"),
        related=[("sante-et-medical", "Santé & Médical"), ("loisirs-culture-et-evenementiel", "Loisirs & Événementiel")],
        zones=[("paris-5", "Paris 5e"), ("paris-13", "Paris 13e"), ("94-val-de-marne", "Val-de-Marne (94)"), ("91-essonne", "Essonne (91)")],
    ),
}
