#!/usr/bin/env python3
"""Données locales UNIQUES par zone (arrondissements + départements) pour le
déploiement du modèle « nettoyage de bureaux ». Chaque zone a son H1, title,
lead, contexte de quartier et son maillage propre → pas de duplicate content.
"""

# Chaque zone : slug, name (H1), short, title, desc, eyebrow, lead,
# p1/p2 (contexte local unique), quartiers (chips), neighbors [(slug,label,sub)]
ARRONDISSEMENTS = {
    "paris-1": dict(
        name="Paris 1er", short="1er", zone="Paris 1er (75001)",
        title="Société de nettoyage de bureaux à Paris 1er (75001) | SPN NET",
        desc="Nettoyage de bureaux dans le 1er arrondissement de Paris : Louvre, Châtelet, Vendôme, Palais-Royal. Interventions soir & matin, ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 1er — 75001",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 1er (75001)",
        lead="Du Louvre à la place Vendôme, nous entretenons les sièges, cabinets et boutiques du 1er arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans jamais gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 1er arrondissement concentre des adresses prestigieuses : le quartier du <b>Louvre</b>, la place <b>Vendôme</b> et ses maisons de luxe, les sièges autour du <b>Palais-Royal</b> et les bureaux du secteur <b>Châtelet-Les Halles</b>, l'un des pôles les plus fréquentés de Paris.",
        p2="Ces espaces exigent une propreté irréprochable et une discrétion totale, souvent dans des immeubles anciens à forte fréquentation. Nos équipes interviennent <span class=\"hl\">avant 9h ou après 18h</span> pour un résultat parfait, sans perturber vos collaborateurs ni vos visiteurs.",
        quartiers=["Louvre", "Place Vendôme", "Palais-Royal", "Châtelet", "Les Halles", "Tuileries", "Saint-Honoré"],
        neighbors=[("paris-2", "Paris 2e", "Bourse, Sentier"), ("paris-4", "Paris 4e", "Marais, Hôtel de Ville"),
                   ("paris-8", "Paris 8e", "Quartier d'affaires"), ("paris-9", "Paris 9e", "Opéra")],
    ),
    "paris-2": dict(
        name="Paris 2e", short="2e", zone="Paris 2e (75002)",
        title="Société de nettoyage de bureaux à Paris 2e (75002) | SPN NET",
        desc="Société de nettoyage de bureaux dans le 2e arrondissement de Paris : Bourse, Sentier, Montorgueil. Interventions soir & matin, ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 2e — 75002",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 2e (75002)",
        lead="De la <b>Bourse</b> au <b>Sentier</b>, nous entretenons les bureaux, sièges et coworkings du 2e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans jamais gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 2e arrondissement concentre une densité rare de bureaux : le quartier d'affaires de la <b>Bourse</b> et des Grands Boulevards, les sièges et agences du <b>Sentier</b> — devenu le « Silicon Sentier » des startups et de la tech —, ainsi que les espaces de coworking autour de <b>Montorgueil</b> et de la rue du Mail.",
        p2="Ces bureaux, souvent installés dans des <b>immeubles haussmanniens</b> aux accès contraints (pas toujours de monte-charge, horaires de gardiennage, plateaux occupés en continu), exigent un prestataire réactif et discret. Nos équipes interviennent <span class=\"hl\">avant 9h ou après 18h</span>, sans perturber votre activité.",
        quartiers=["Quartier de la Bourse", "Le Sentier", "Montorgueil", "Rue du Mail", "Vivienne", "Gaillon", "Grands Boulevards"],
        neighbors=[("paris-1", "Paris 1er", "Louvre, Châtelet"), ("paris-3", "Paris 3e", "Haut-Marais"),
                   ("paris-9", "Paris 9e", "Opéra, Grands Boulevards"), ("paris-10", "Paris 10e", "Canal Saint-Martin")],
    ),
    "paris-3": dict(
        name="Paris 3e", short="3e", zone="Paris 3e (75003)",
        title="Société de nettoyage de bureaux à Paris 3e (75003) | SPN NET",
        desc="Nettoyage de bureaux dans le 3e arrondissement : Haut-Marais, Arts-et-Métiers, Temple. Agences, studios, galeries. Interventions soir & matin, ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 3e — 75003",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 3e (75003)",
        lead="Du Haut-Marais aux Arts-et-Métiers, nous entretenons les agences, studios et galeries du 3e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 3e arrondissement, cœur du <b>Haut-Marais</b>, mêle agences de communication, studios de création, galeries d'art et jeunes marques. Les quartiers du <b>Temple</b> et des <b>Arts-et-Métiers</b> abritent de nombreuses PME et professions créatives.",
        p2="Ces bureaux, souvent installés dans d'anciens hôtels particuliers et ateliers réhabilités, demandent un entretien soigné et respectueux des lieux. Nos équipes s'adaptent à ces espaces atypiques et interviennent en horaires décalés.",
        quartiers=["Haut-Marais", "Arts-et-Métiers", "Le Temple", "Enfants-Rouges", "Square du Temple", "Rue de Bretagne"],
        neighbors=[("paris-2", "Paris 2e", "Bourse, Sentier"), ("paris-4", "Paris 4e", "Marais Sud"),
                   ("paris-10", "Paris 10e", "Canal Saint-Martin"), ("paris-11", "Paris 11e", "République")],
    ),
    "paris-4": dict(
        name="Paris 4e", short="4e", zone="Paris 4e (75004)",
        title="Société de nettoyage de bureaux à Paris 4e (75004) | SPN NET",
        desc="Nettoyage de bureaux dans le 4e arrondissement : Marais, Hôtel de Ville, Île de la Cité, BHV. Interventions soir & matin, ISO 45001, avis 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 4e — 75004",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 4e (75004)",
        lead="Du Marais à l'Hôtel de Ville, nous entretenons bureaux, commerces et espaces administratifs du 4e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, en toute discrétion. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 4e arrondissement réunit le <b>Marais</b> historique, le pôle de l'<b>Hôtel de Ville</b> et du BHV, ainsi que l'<b>Île de la Cité</b> et l'<b>Île Saint-Louis</b>. Un secteur dense en commerces, agences et administrations.",
        p2="Entre immeubles classés et fort passage touristique, la propreté y est un enjeu d'image permanent. Nous adaptons fréquence et protocole à chaque type de local, en intervenant hors des heures d'ouverture.",
        quartiers=["Le Marais", "Hôtel de Ville", "Île de la Cité", "Île Saint-Louis", "Saint-Paul", "BHV"],
        neighbors=[("paris-3", "Paris 3e", "Haut-Marais"), ("paris-1", "Paris 1er", "Châtelet"),
                   ("paris-11", "Paris 11e", "Bastille"), ("paris-12", "Paris 12e", "Gare de Lyon")],
    ),
    "paris-5": dict(
        name="Paris 5e", short="5e", zone="Paris 5e (75005)",
        title="Société de nettoyage de bureaux à Paris 5e (75005) | SPN NET",
        desc="Nettoyage de bureaux dans le 5e arrondissement : Quartier Latin, Sorbonne, Jussieu. Enseignement, édition, recherche. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 5e — 75005",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 5e (75005)",
        lead="Au cœur du Quartier Latin, nous entretenons bureaux, cabinets et établissements du 5e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 5e arrondissement, celui du <b>Quartier Latin</b>, de la <b>Sorbonne</b> et de <b>Jussieu</b>, concentre l'enseignement supérieur, la recherche, l'édition et de nombreux cabinets (avocats, professions libérales).",
        p2="Ces environnements studieux exigent hygiène et régularité, souvent dans des bâtiments anciens. Nos équipes assurent un entretien discret et méthodique, en horaires décalés pour ne pas perturber cours et consultations.",
        quartiers=["Quartier Latin", "Sorbonne", "Jussieu", "Panthéon", "Mouffetard", "Saint-Michel"],
        neighbors=[("paris-6", "Paris 6e", "Saint-Germain"), ("paris-13", "Paris 13e", "Bibliothèque"),
                   ("paris-4", "Paris 4e", "Île de la Cité"), ("paris-14", "Paris 14e", "Montparnasse")],
    ),
    "paris-6": dict(
        name="Paris 6e", short="6e", zone="Paris 6e (75006)",
        title="Société de nettoyage de bureaux à Paris 6e (75006) | SPN NET",
        desc="Nettoyage de bureaux dans le 6e arrondissement : Saint-Germain-des-Prés, Odéon, Luxembourg. Édition, galeries, professions libérales. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 6e — 75006",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 6e (75006)",
        lead="À Saint-Germain-des-Prés, nous entretenons cabinets, maisons d'édition et galeries du 6e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, en toute discrétion. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 6e arrondissement, autour de <b>Saint-Germain-des-Prés</b>, de l'<b>Odéon</b> et du <b>Luxembourg</b>, réunit maisons d'édition, galeries, cabinets d'avocats et enseignes de luxe dans un cadre patrimonial d'exception.",
        p2="L'exigence y est maximale : discrétion, finitions soignées et respect des matériaux nobles. Nos équipes formées interviennent hors ouverture pour une propreté à la hauteur de ces adresses.",
        quartiers=["Saint-Germain-des-Prés", "Odéon", "Luxembourg", "Saint-Sulpice", "Mabillon", "Rennes"],
        neighbors=[("paris-5", "Paris 5e", "Quartier Latin"), ("paris-7", "Paris 7e", "Invalides"),
                   ("paris-14", "Paris 14e", "Montparnasse"), ("paris-15", "Paris 15e", "Convention")],
    ),
    "paris-7": dict(
        name="Paris 7e", short="7e", zone="Paris 7e (75007)",
        title="Société de nettoyage de bureaux à Paris 7e (75007) | SPN NET",
        desc="Nettoyage de bureaux dans le 7e arrondissement : Invalides, Tour Eiffel, Assemblée, ministères. Institutionnel, ambassades. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 7e — 75007",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 7e (75007)",
        lead="Des Invalides au Champ-de-Mars, nous entretenons bureaux, sièges et espaces institutionnels du 7e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, en toute discrétion. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 7e arrondissement abrite institutions, ministères et ambassades autour des <b>Invalides</b>, de l'<b>Assemblée nationale</b> et de la <b>Tour Eiffel</b>, aux côtés de sièges d'entreprises et de cabinets prestigieux.",
        p2="Ces environnements sensibles imposent rigueur, fiabilité et confidentialité. Nos équipes, habituées aux exigences institutionnelles, interviennent en horaires décalés avec un protocole maîtrisé.",
        quartiers=["Invalides", "Champ-de-Mars", "Gros-Caillou", "École Militaire", "Rue Cler", "Sèvres-Babylone"],
        neighbors=[("paris-6", "Paris 6e", "Saint-Germain"), ("paris-15", "Paris 15e", "Front de Seine"),
                   ("paris-8", "Paris 8e", "Quartier d'affaires"), ("92-hauts-de-seine", "Hauts-de-Seine", "Boulogne, Issy")],
    ),
    "paris-8": dict(
        name="Paris 8e", short="8e", zone="Paris 8e (75008)",
        title="Société de nettoyage de bureaux à Paris 8e (75008) | SPN NET",
        desc="Nettoyage de bureaux dans le 8e arrondissement : Champs-Élysées, Madeleine, Monceau. Quartier d'affaires, sièges sociaux. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 8e — 75008",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 8e (75008)",
        lead="Des Champs-Élysées à la Madeleine, nous entretenons les sièges et bureaux du principal quartier d'affaires parisien. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 8e arrondissement est l'un des grands <b>quartiers d'affaires</b> de Paris : sièges sociaux, banques et grands comptes le long des <b>Champs-Élysées</b>, autour de la <b>Madeleine</b>, de <b>Saint-Lazare</b> et du parc <b>Monceau</b>.",
        p2="Immeubles de prestige, forte fréquentation, image de marque : la propreté y est stratégique. Nos équipes assurent un entretien haut de gamme, en horaires décalés, avec un interlocuteur dédié pour vos sites.",
        quartiers=["Champs-Élysées", "Madeleine", "Monceau", "Saint-Lazare", "Miromesnil", "Franklin-Roosevelt"],
        neighbors=[("paris-9", "Paris 9e", "Opéra"), ("paris-17", "Paris 17e", "Batignolles"),
                   ("paris-16", "Paris 16e", "Trocadéro"), ("92-hauts-de-seine", "Hauts-de-Seine", "La Défense")],
    ),
    "paris-9": dict(
        name="Paris 9e", short="9e", zone="Paris 9e (75009)",
        title="Société de nettoyage de bureaux à Paris 9e (75009) | SPN NET",
        desc="Nettoyage de bureaux dans le 9e arrondissement : Opéra, Grands Boulevards, Trinité. Banques, assurances, sièges. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 9e — 75009",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 9e (75009)",
        lead="De l'Opéra aux Grands Boulevards, nous entretenons les bureaux, banques et sièges du 9e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 9e arrondissement, autour de l'<b>Opéra</b>, des <b>Grands Boulevards</b> et de la <b>Trinité</b>, est un pôle majeur de la banque, de l'assurance et des sièges sociaux, doublé d'un quartier commerçant très actif.",
        p2="Plateaux de bureaux, agences et grands magasins y cohabitent, avec des flux importants. Nos équipes interviennent tôt le matin ou en soirée pour garantir des espaces impeccables à l'ouverture.",
        quartiers=["Opéra", "Grands Boulevards", "Trinité", "Pigalle", "Chaussée-d'Antin", "Saint-Georges"],
        neighbors=[("paris-8", "Paris 8e", "Quartier d'affaires"), ("paris-2", "Paris 2e", "Bourse"),
                   ("paris-10", "Paris 10e", "Gare du Nord"), ("paris-18", "Paris 18e", "Montmartre")],
    ),
    "paris-10": dict(
        name="Paris 10e", short="10e", zone="Paris 10e (75010)",
        title="Société de nettoyage de bureaux à Paris 10e (75010) | SPN NET",
        desc="Nettoyage de bureaux dans le 10e arrondissement : Gare du Nord, Gare de l'Est, Canal Saint-Martin. Startups, coworkings. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 10e — 75010",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 10e (75010)",
        lead="Du Canal Saint-Martin aux gares du Nord et de l'Est, nous entretenons bureaux, startups et coworkings du 10e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 10e arrondissement, entre <b>Gare du Nord</b>, <b>Gare de l'Est</b> et <b>Canal Saint-Martin</b>, est devenu un pôle dynamique de startups, d'agences et d'espaces de coworking, dans d'anciens ateliers reconvertis.",
        p2="Ces bureaux jeunes et ouverts recherchent un prestataire souple et réactif. Nous adaptons la fréquence à votre activité et intervenons en horaires décalés, sans perturber vos équipes.",
        quartiers=["Canal Saint-Martin", "Gare du Nord", "Gare de l'Est", "Château d'Eau", "Faubourg Saint-Denis", "Récollets"],
        neighbors=[("paris-9", "Paris 9e", "Opéra"), ("paris-11", "Paris 11e", "République"),
                   ("paris-3", "Paris 3e", "Haut-Marais"), ("paris-19", "Paris 19e", "La Villette")],
    ),
    "paris-11": dict(
        name="Paris 11e", short="11e", zone="Paris 11e (75011)",
        title="Société de nettoyage de bureaux à Paris 11e (75011) | SPN NET",
        desc="Nettoyage de bureaux dans le 11e arrondissement : Bastille, Oberkampf, République. Agences, tech, PME. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 11e — 75011",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 11e (75011)",
        lead="De Bastille à Oberkampf, nous entretenons les bureaux, agences et PME du 11e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, sans gêner votre activité. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 11e arrondissement, entre <b>Bastille</b>, <b>Oberkampf</b> et <b>République</b>, est l'un des plus vivants de Paris : agences, studios, entreprises tech et PME y sont très nombreux.",
        p2="Bureaux ouverts, horaires étendus et forte densité caractérisent le secteur. Nos équipes interviennent tôt ou tard pour un entretien régulier et fiable, calibré à votre rythme.",
        quartiers=["Bastille", "Oberkampf", "République", "Charonne", "Voltaire", "Père-Lachaise"],
        neighbors=[("paris-3", "Paris 3e", "Haut-Marais"), ("paris-12", "Paris 12e", "Nation"),
                   ("paris-10", "Paris 10e", "Canal Saint-Martin"), ("paris-20", "Paris 20e", "Ménilmontant")],
    ),
    "paris-12": dict(
        name="Paris 12e", short="12e", zone="Paris 12e (75012)",
        title="Société de nettoyage de bureaux à Paris 12e (75012) | SPN NET",
        desc="Nettoyage de bureaux dans le 12e arrondissement : Bercy, Gare de Lyon, Nation, Daumesnil. Sièges, administrations. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 12e — 75012",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 12e (75012)",
        lead="De Bercy à la Gare de Lyon, nous entretenons les sièges, administrations et bureaux du 12e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 12e arrondissement accueille de grands sièges et administrations à <b>Bercy</b>, le pôle d'affaires de la <b>Gare de Lyon</b>, ainsi que les quartiers de <b>Nation</b> et <b>Daumesnil</b>.",
        p2="Grands plateaux, immeubles récents et forte affluence appellent un entretien structuré. Nos équipes interviennent en horaires décalés, avec un suivi qualité régulier pour des locaux toujours nets.",
        quartiers=["Bercy", "Gare de Lyon", "Nation", "Daumesnil", "Aligre", "Reuilly"],
        neighbors=[("paris-11", "Paris 11e", "Bastille"), ("paris-13", "Paris 13e", "Bibliothèque"),
                   ("paris-4", "Paris 4e", "Marais"), ("94-val-de-marne", "Val-de-Marne", "Ivry, Charenton")],
    ),
    "paris-13": dict(
        name="Paris 13e", short="13e", zone="Paris 13e (75013)",
        title="Société de nettoyage de bureaux à Paris 13e (75013) | SPN NET",
        desc="Nettoyage de bureaux dans le 13e arrondissement : Bibliothèque, Station F, Butte-aux-Cailles. Tech, université, sièges. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 13e — 75013",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 13e (75013)",
        lead="De la Bibliothèque à Station F, nous entretenons les bureaux, campus tech et sièges du 13e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 13e arrondissement est un pôle d'innovation : quartier <b>Paris Rive Gauche</b> et <b>Bibliothèque François-Mitterrand</b>, campus universitaires et le plus grand incubateur de startups d'Europe, <b>Station F</b>.",
        p2="Espaces de travail modernes, coworkings et grands sièges y côtoient un tissu de PME. Nous adaptons nos prestations à ces environnements exigeants et interviennent hors des heures de bureau.",
        quartiers=["Paris Rive Gauche", "Bibliothèque", "Station F", "Butte-aux-Cailles", "Place d'Italie", "Les Gobelins"],
        neighbors=[("paris-5", "Paris 5e", "Quartier Latin"), ("paris-12", "Paris 12e", "Bercy"),
                   ("paris-14", "Paris 14e", "Montparnasse"), ("94-val-de-marne", "Val-de-Marne", "Ivry, Le Kremlin")],
    ),
    "paris-14": dict(
        name="Paris 14e", short="14e", zone="Paris 14e (75014)",
        title="Société de nettoyage de bureaux à Paris 14e (75014) | SPN NET",
        desc="Nettoyage de bureaux dans le 14e arrondissement : Montparnasse, Denfert, Alésia. Bureaux, santé, sièges. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 14e — 75014",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 14e (75014)",
        lead="Autour de Montparnasse, nous entretenons bureaux, cabinets et établissements du 14e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 14e arrondissement s'organise autour de <b>Montparnasse</b>, pôle de bureaux et de transports, de <b>Denfert-Rochereau</b> et d'<b>Alésia</b>, avec une forte présence de cabinets et d'établissements de santé.",
        p2="Tours tertiaires, cliniques et professions libérales y coexistent. Nos équipes assurent un entretien rigoureux, adapté aux exigences d'hygiène du secteur, en horaires décalés.",
        quartiers=["Montparnasse", "Denfert-Rochereau", "Alésia", "Pernety", "Plaisance", "Mouton-Duvernet"],
        neighbors=[("paris-15", "Paris 15e", "Convention"), ("paris-6", "Paris 6e", "Saint-Germain"),
                   ("paris-13", "Paris 13e", "Bibliothèque"), ("92-hauts-de-seine", "Hauts-de-Seine", "Malakoff, Montrouge")],
    ),
    "paris-15": dict(
        name="Paris 15e", short="15e", zone="Paris 15e (75015)",
        title="Société de nettoyage de bureaux à Paris 15e (75015) | SPN NET",
        desc="Nettoyage de bureaux dans le 15e arrondissement : Beaugrenelle, Convention, Front de Seine. Sièges, tours, PME. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 15e — 75015",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 15e (75015)",
        lead="Du Front de Seine à la Convention, nous entretenons les sièges, tours et bureaux du 15e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 15e, arrondissement le plus peuplé de Paris, concentre de grands sièges le long du <b>Front de Seine</b> (Beaugrenelle), autour de la <b>Convention</b>, de <b>Vaugirard</b> et de la gare <b>Montparnasse</b>.",
        p2="Tours de bureaux, plateaux et PME y génèrent des besoins d'entretien importants et réguliers. Nos équipes interviennent en horaires décalés avec un interlocuteur dédié, pour un résultat constant.",
        quartiers=["Beaugrenelle", "Front de Seine", "Convention", "Vaugirard", "Grenelle", "Pasteur"],
        neighbors=[("paris-7", "Paris 7e", "Invalides"), ("paris-14", "Paris 14e", "Montparnasse"),
                   ("paris-16", "Paris 16e", "Trocadéro"), ("92-hauts-de-seine", "Hauts-de-Seine", "Issy, Boulogne")],
    ),
    "paris-16": dict(
        name="Paris 16e", short="16e", zone="Paris 16e (75016)",
        title="Société de nettoyage de bureaux à Paris 16e (75016) | SPN NET",
        desc="Nettoyage de bureaux dans le 16e arrondissement : Trocadéro, Auteuil, Passy, Étoile. Sièges, professions libérales. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 16e — 75016",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 16e (75016)",
        lead="Du Trocadéro à Auteuil, nous entretenons sièges, cabinets et bureaux du 16e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>, en toute discrétion. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 16e arrondissement, résidentiel et d'affaires, réunit sièges d'entreprises et professions libérales autour du <b>Trocadéro</b>, de <b>Passy</b>, d'<b>Auteuil</b> et de l'avenue de la <b>Grande Armée</b> (Étoile).",
        p2="Immeubles haussmanniens de standing et clientèle exigeante imposent une propreté irréprochable et discrète. Nos équipes formées interviennent hors ouverture, avec un protocole soigné.",
        quartiers=["Trocadéro", "Passy", "Auteuil", "Étoile", "La Muette", "Chaillot"],
        neighbors=[("paris-8", "Paris 8e", "Quartier d'affaires"), ("paris-15", "Paris 15e", "Front de Seine"),
                   ("paris-17", "Paris 17e", "Batignolles"), ("92-hauts-de-seine", "Hauts-de-Seine", "Boulogne, Neuilly")],
    ),
    "paris-17": dict(
        name="Paris 17e", short="17e", zone="Paris 17e (75017)",
        title="Société de nettoyage de bureaux à Paris 17e (75017) | SPN NET",
        desc="Nettoyage de bureaux dans le 17e arrondissement : Batignolles, Clichy, Palais des Congrès, Étoile. Nouveau quartier d'affaires. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 17e — 75017",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 17e (75017)",
        lead="Des Batignolles au Palais des Congrès, nous entretenons les bureaux et sièges du 17e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 17e arrondissement se transforme avec le nouveau quartier d'affaires <b>Clichy-Batignolles</b> (tribunal de Paris, immeubles neufs), aux côtés des pôles établis de l'<b>Étoile</b>, des <b>Ternes</b> et du <b>Palais des Congrès</b>.",
        p2="Bureaux récents à haute exigence environnementale et immeubles classiques y cohabitent. Nos équipes interviennent en horaires décalés, avec un suivi qualité adapté à chaque site.",
        quartiers=["Batignolles", "Clichy-Batignolles", "Ternes", "Palais des Congrès", "Wagram", "Monceau"],
        neighbors=[("paris-8", "Paris 8e", "Quartier d'affaires"), ("paris-16", "Paris 16e", "Étoile"),
                   ("paris-18", "Paris 18e", "Montmartre"), ("92-hauts-de-seine", "Hauts-de-Seine", "Levallois, Clichy")],
    ),
    "paris-18": dict(
        name="Paris 18e", short="18e", zone="Paris 18e (75018)",
        title="Société de nettoyage de bureaux à Paris 18e (75018) | SPN NET",
        desc="Nettoyage de bureaux dans le 18e arrondissement : Montmartre, Clignancourt, La Chapelle. Commerces, PME, agences. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 18e — 75018",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 18e (75018)",
        lead="De Montmartre à La Chapelle, nous entretenons bureaux, commerces et PME du 18e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 18e arrondissement mêle le pôle touristique de <b>Montmartre</b>, les quartiers commerçants de <b>Clignancourt</b> et de <b>Barbès</b>, et le secteur en mutation de <b>La Chapelle</b>, riche en PME et agences.",
        p2="Locaux variés, du commerce à l'atelier, et forte fréquentation : la propreté y soutient l'activité au quotidien. Nous adaptons fréquence et protocole, en intervenant en horaires décalés.",
        quartiers=["Montmartre", "Clignancourt", "La Chapelle", "Barbès", "Jules-Joffrin", "La Goutte d'Or"],
        neighbors=[("paris-9", "Paris 9e", "Pigalle"), ("paris-17", "Paris 17e", "Batignolles"),
                   ("paris-19", "Paris 19e", "La Villette"), ("93-seine-saint-denis", "Seine-Saint-Denis", "Saint-Ouen, Saint-Denis")],
    ),
    "paris-19": dict(
        name="Paris 19e", short="19e", zone="Paris 19e (75019)",
        title="Société de nettoyage de bureaux à Paris 19e (75019) | SPN NET",
        desc="Nettoyage de bureaux dans le 19e arrondissement : La Villette, Buttes-Chaumont, Stalingrad. PME, sièges, pôles culturels. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 19e — 75019",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 19e (75019)",
        lead="De La Villette aux Buttes-Chaumont, nous entretenons bureaux, PME et pôles culturels du 19e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 19e arrondissement, autour du parc de <b>La Villette</b> (Cité des sciences, Philharmonie), des <b>Buttes-Chaumont</b> et du <b>Bassin de la Villette</b>, accueille PME, sièges et de grands équipements culturels.",
        p2="Grands espaces recevant du public et bureaux de proximité y génèrent des besoins d'entretien diversifiés. Nos équipes interviennent en horaires décalés, avec un protocole adapté à chaque site.",
        quartiers=["La Villette", "Buttes-Chaumont", "Stalingrad", "Bassin de la Villette", "Jaurès", "Ourcq"],
        neighbors=[("paris-10", "Paris 10e", "Gare de l'Est"), ("paris-18", "Paris 18e", "La Chapelle"),
                   ("paris-20", "Paris 20e", "Belleville"), ("93-seine-saint-denis", "Seine-Saint-Denis", "Pantin, Aubervilliers")],
    ),
    "paris-20": dict(
        name="Paris 20e", short="20e", zone="Paris 20e (75020)",
        title="Société de nettoyage de bureaux à Paris 20e (75020) | SPN NET",
        desc="Nettoyage de bureaux dans le 20e arrondissement : Belleville, Ménilmontant, Gambetta, Père-Lachaise. PME, associations, agences. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Paris 20e — 75020",
        h1="Société de <em>nettoyage de bureaux</em> à Paris 20e (75020)",
        lead="De Belleville à Gambetta, nous entretenons bureaux, PME et associations du 20e arrondissement. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le 20e arrondissement, vivant et créatif, s'étend de <b>Belleville</b> à <b>Ménilmontant</b> et <b>Gambetta</b>, avec un tissu dense de PME, d'associations, d'ateliers d'artistes et d'agences.",
        p2="Locaux de proximité et espaces partagés y dominent. Nous proposons un entretien souple et régulier, calibré à votre activité, en intervenant tôt le matin ou en soirée.",
        quartiers=["Belleville", "Ménilmontant", "Gambetta", "Père-Lachaise", "Saint-Blaise", "Télégraphe"],
        neighbors=[("paris-11", "Paris 11e", "Bastille"), ("paris-19", "Paris 19e", "La Villette"),
                   ("paris-12", "Paris 12e", "Nation"), ("93-seine-saint-denis", "Seine-Saint-Denis", "Montreuil, Bagnolet")],
    ),
}

DEPARTEMENTS = {
    "92-hauts-de-seine": dict(
        name="Hauts-de-Seine (92)", short="92", zone="Hauts-de-Seine (92)",
        title="Société de nettoyage de bureaux dans les Hauts-de-Seine (92) | SPN NET",
        desc="Nettoyage de bureaux dans les Hauts-de-Seine : La Défense, Boulogne, Issy, Nanterre, Levallois. Notre base à Bagneux. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Hauts-de-Seine (92)",
        h1="Société de <em>nettoyage de bureaux</em> dans les Hauts-de-Seine (92)",
        lead="De La Défense à Boulogne, nous entretenons les sièges et bureaux des Hauts-de-Seine — le département où se trouve notre base. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Les Hauts-de-Seine forment le premier pôle tertiaire d'Île-de-France avec <b>La Défense</b>, <b>Boulogne-Billancourt</b>, <b>Issy-les-Moulineaux</b>, <b>Nanterre</b> et <b>Levallois-Perret</b> : sièges sociaux, tours et campus d'entreprises.",
        p2="Notre siège est à <b>Bagneux</b>, au cœur du département : nous y sommes particulièrement réactifs. Nos équipes interviennent en horaires décalés sur tous types de locaux, du plateau tertiaire à la PME.",
        quartiers=["La Défense", "Boulogne-Billancourt", "Issy-les-Moulineaux", "Nanterre", "Levallois-Perret", "Bagneux", "Clamart", "Montrouge"],
        neighbors=[("paris-8", "Paris 8e", "Quartier d'affaires"), ("paris-15", "Paris 15e", "Front de Seine"),
                   ("paris-16", "Paris 16e", "Trocadéro"), ("94-val-de-marne", "Val-de-Marne", "Département voisin")],
    ),
    "93-seine-saint-denis": dict(
        name="Seine-Saint-Denis (93)", short="93", zone="Seine-Saint-Denis (93)",
        title="Société de nettoyage de bureaux en Seine-Saint-Denis (93) | SPN NET",
        desc="Nettoyage de bureaux en Seine-Saint-Denis : Saint-Denis, Montreuil, Saint-Ouen, Pantin, Plaine Commune. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Seine-Saint-Denis (93)",
        h1="Société de <em>nettoyage de bureaux</em> en Seine-Saint-Denis (93)",
        lead="De Saint-Denis à Montreuil, nous entretenons les bureaux et sièges de Seine-Saint-Denis. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="La Seine-Saint-Denis connaît un fort essor tertiaire : le pôle <b>Plaine Commune</b> à <b>Saint-Denis</b>, les sièges de <b>Saint-Ouen</b>, <b>Pantin</b> et <b>Montreuil</b> accueillent de nombreux grands comptes et PME.",
        p2="Immeubles neufs, zones d'activité et bureaux de proximité s'y côtoient. Nos équipes interviennent en horaires décalés, avec un entretien fiable et un interlocuteur dédié.",
        quartiers=["Saint-Denis", "Plaine Commune", "Saint-Ouen", "Pantin", "Montreuil", "Aubervilliers", "Bagnolet", "Noisy-le-Grand"],
        neighbors=[("paris-18", "Paris 18e", "La Chapelle"), ("paris-19", "Paris 19e", "La Villette"),
                   ("paris-20", "Paris 20e", "Belleville"), ("94-val-de-marne", "Val-de-Marne", "Département voisin")],
    ),
    "94-val-de-marne": dict(
        name="Val-de-Marne (94)", short="94", zone="Val-de-Marne (94)",
        title="Société de nettoyage de bureaux dans le Val-de-Marne (94) | SPN NET",
        desc="Nettoyage de bureaux dans le Val-de-Marne : Créteil, Ivry, Vitry, Rungis, Charenton. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Val-de-Marne (94)",
        h1="Société de <em>nettoyage de bureaux</em> dans le Val-de-Marne (94)",
        lead="De Créteil à Rungis, nous entretenons bureaux, sièges et plateformes du Val-de-Marne. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le Val-de-Marne réunit le pôle administratif de <b>Créteil</b>, les quartiers d'affaires d'<b>Ivry</b> et de <b>Charenton</b>, et la grande plateforme logistique et tertiaire de <b>Rungis</b>.",
        p2="Bureaux, administrations et sites d'activité y génèrent des besoins d'entretien variés. Proches (notre base à Bagneux jouxte le département), nos équipes interviennent en horaires décalés.",
        quartiers=["Créteil", "Ivry-sur-Seine", "Vitry-sur-Seine", "Rungis", "Charenton", "Le Kremlin-Bicêtre", "Maisons-Alfort"],
        neighbors=[("paris-12", "Paris 12e", "Bercy"), ("paris-13", "Paris 13e", "Bibliothèque"),
                   ("92-hauts-de-seine", "Hauts-de-Seine", "Département voisin"), ("93-seine-saint-denis", "Seine-Saint-Denis", "Département voisin")],
    ),
    "77-seine-et-marne": dict(
        name="Seine-et-Marne (77)", short="77", zone="Seine-et-Marne (77)",
        title="Société de nettoyage de bureaux en Seine-et-Marne (77) | SPN NET",
        desc="Nettoyage de bureaux en Seine-et-Marne : Marne-la-Vallée, Meaux, Melun, Chelles. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Seine-et-Marne (77)",
        h1="Société de <em>nettoyage de bureaux</em> en Seine-et-Marne (77)",
        lead="De Marne-la-Vallée à Melun, nous entretenons bureaux et sièges de Seine-et-Marne. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="La Seine-et-Marne accueille de grands pôles tertiaires à <b>Marne-la-Vallée</b> (Val d'Europe, Bussy), les bureaux de <b>Meaux</b>, de <b>Melun</b> et de <b>Chelles</b>, ainsi que des parcs d'activité en développement.",
        p2="Sièges, zones d'activité et PME y ont des besoins d'entretien réguliers. Nos équipes interviennent en horaires décalés, avec un protocole adapté à chaque site.",
        quartiers=["Marne-la-Vallée", "Val d'Europe", "Meaux", "Melun", "Chelles", "Bussy-Saint-Georges", "Torcy"],
        neighbors=[("93-seine-saint-denis", "Seine-Saint-Denis", "Département voisin"), ("94-val-de-marne", "Val-de-Marne", "Département voisin"),
                   ("paris-12", "Paris 12e", "Gare de Lyon"), ("tertiaire", "Nettoyage tertiaire", "Notre pôle bureaux")],
    ),
    "78-yvelines": dict(
        name="Yvelines (78)", short="78", zone="Yvelines (78)",
        title="Société de nettoyage de bureaux dans les Yvelines (78) | SPN NET",
        desc="Nettoyage de bureaux dans les Yvelines : Versailles, Saint-Quentin-en-Yvelines, Vélizy, Montigny. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Yvelines (78)",
        h1="Société de <em>nettoyage de bureaux</em> dans les Yvelines (78)",
        lead="De Versailles à Vélizy, nous entretenons bureaux, sièges et technopôles des Yvelines. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Les Yvelines réunissent de grands pôles d'emploi : <b>Saint-Quentin-en-Yvelines</b>, <b>Vélizy-Villacoublay</b> (technopôle, automobile, aéronautique), <b>Versailles</b> et <b>Montigny</b>, avec sièges et centres de R&D.",
        p2="Campus d'entreprises et parcs d'activité y demandent un entretien structuré et fiable. Nos équipes interviennent en horaires décalés, avec un suivi qualité régulier.",
        quartiers=["Versailles", "Saint-Quentin-en-Yvelines", "Vélizy-Villacoublay", "Montigny-le-Bretonneux", "Guyancourt", "Poissy"],
        neighbors=[("92-hauts-de-seine", "Hauts-de-Seine", "Département voisin"), ("91-essonne", "Essonne", "Département voisin"),
                   ("paris-15", "Paris 15e", "Front de Seine"), ("tertiaire", "Nettoyage tertiaire", "Notre pôle bureaux")],
    ),
    "91-essonne": dict(
        name="Essonne (91)", short="91", zone="Essonne (91)",
        title="Société de nettoyage de bureaux dans l'Essonne (91) | SPN NET",
        desc="Nettoyage de bureaux dans l'Essonne : Évry, Massy, Plateau de Saclay, Les Ulis. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Essonne (91)",
        h1="Société de <em>nettoyage de bureaux</em> dans l'Essonne (91)",
        lead="d'Évry au Plateau de Saclay, nous entretenons bureaux, laboratoires et sièges de l'Essonne. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="L'Essonne abrite un pôle scientifique majeur : le <b>Plateau de Saclay</b> (universités, laboratoires, R&D), les bureaux de <b>Massy</b>, d'<b>Évry-Courcouronnes</b> et la zone d'activité des <b>Ulis</b>.",
        p2="Sièges, centres de recherche et parcs tertiaires y exigent rigueur et protocoles adaptés. Nos équipes interviennent en horaires décalés, avec un entretien fiable et traçable.",
        quartiers=["Évry-Courcouronnes", "Massy", "Plateau de Saclay", "Les Ulis", "Palaiseau", "Corbeil-Essonnes"],
        neighbors=[("94-val-de-marne", "Val-de-Marne", "Département voisin"), ("78-yvelines", "Yvelines", "Département voisin"),
                   ("paris-13", "Paris 13e", "Rive Gauche"), ("tertiaire", "Nettoyage tertiaire", "Notre pôle bureaux")],
    ),
    "95-val-doise": dict(
        name="Val-d'Oise (95)", short="95", zone="Val-d'Oise (95)",
        title="Société de nettoyage de bureaux dans le Val-d'Oise (95) | SPN NET",
        desc="Nettoyage de bureaux dans le Val-d'Oise : Cergy-Pontoise, Roissy, Argenteuil, Sarcelles. ISO 45001, 4,8/5. Devis 24h.",
        eyebrow="Nettoyage de bureaux · Val-d'Oise (95)",
        h1="Société de <em>nettoyage de bureaux</em> dans le Val-d'Oise (95)",
        lead="De Cergy-Pontoise à Roissy, nous entretenons bureaux, sièges et plateformes du Val-d'Oise. Interventions <span class=\"hl\">avant 9h ou après 18h</span>. Équipe dédiée, certifiée ISO 45001 — <span class=\"hl\">devis sous 24h</span>.",
        p1="Le Val-d'Oise réunit le pôle tertiaire et universitaire de <b>Cergy-Pontoise</b>, la vaste zone d'affaires et logistique de <b>Roissy-Charles-de-Gaulle</b>, ainsi que les bureaux d'<b>Argenteuil</b> et de <b>Sarcelles</b>.",
        p2="Sièges, plateformes et parcs d'activité y génèrent des besoins d'entretien soutenus. Nos équipes interviennent en horaires décalés, avec un protocole adapté à chaque site.",
        quartiers=["Cergy-Pontoise", "Roissy-en-France", "Argenteuil", "Sarcelles", "Franconville", "Gonesse"],
        neighbors=[("93-seine-saint-denis", "Seine-Saint-Denis", "Département voisin"), ("92-hauts-de-seine", "Hauts-de-Seine", "Département voisin"),
                   ("paris-17", "Paris 17e", "Batignolles"), ("tertiaire", "Nettoyage tertiaire", "Notre pôle bureaux")],
    ),
}

# Ordre de déploiement : arrondissements prioritaires GSC d'abord, puis le reste, puis départements
ALL_ZONES = {**{k: v for k, v in ARRONDISSEMENTS.items() if v}, **DEPARTEMENTS}
